# Site settings
title: Tech @ Fer Perales
email: me@ferperales.net
description: > # this means to ignore newlines until "baseurl:"
  A blog where I share tech posts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech.ferperales.net" # the base hostname & protocol for your site
twitter_username: FerPeralesM
github_username:  ferperales

# Build settings
markdown: kramdown

# Custom permalink
permalink: /:year/:month/:title

# Pagination
paginate: 5

# Analytics
google_analytics_tracking_id: UA-61502396-1
